version: "1"

services:
  db:
    build: ./db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=devcamp
    ports:
      - 5555:5432
    volumes:
      - ./db/db-data:/var/lib/postgresql/data